### PR TITLE
Added ability to configure qBittorrent category and share limits.

### PR DESCRIPTION
**Pull request by jonbenta**

### CODE REVIEW

**Comment by L4GSP1KE** [comment]
I like the categories, however I can't think of anything positive that would come from making share limits convenient. Is there a reason that I'm overlooking?

**Comment by jonbenta** [comment]
> I like the categories, however I can't think of anything positive that would come from making share limits convenient. Is there a reason that I'm overlooking?

I personally use different share limits when I'm uploading versus when I'm downloading so having them configurable here saves me from having to manually set those limits on every torrent I upload with Upload-Assistant. Granted, share limits per tracker would probably make more sense but the same argument could be made for categories and tags.

**Comment by L4GSP1KE** [comment]
I don't think I expressed myself clearly enough. I worry that conveniently offering ratio/seed time limits could hurt retention beyond the minimum requirements. With the addition of categories/tags it would be trivial to have something separate manage limits based on those. What do you think?

I agree that categories/tags would make more sense on a per-tracker basis.

**Comment by jonbenta** [comment]
> I don't think I expressed myself clearly enough. I worry that conveniently offering ratio/seed time limits could hurt retention beyond the minimum requirements. With the addition of categories/tags it would be trivial to have something separate manage limits based on those. What do you think?
> 
> I agree that categories/tags would make more sense on a per-tracker basis.

Fair enough. In that case, I'll whittle this PR down to the addition of category.
Mind elaborating on the "something separate manage limits" piece?

**Comment by L4GSP1KE** [comment]
Tools like qbittools/qbit-race might be able to do what you're looking for, or a simple script like [this](https://gist.github.com/L4GSP1KE/3201bf9bae20ef3c42eb709cf1399543) set to run on a schedule

**Comment by costaht** [comment]
I'd love to have the option to set a seed time for different trackers.

**Pull request closed without merging**
