### PR TITLE
Update LST.py

### PR DESCRIPTION
**Pull request by LostRager**
added ability to upload hentai easier.

### CODE REVIEW

**Comment by LostRager** [comment]
Probably a way cleaner way of doing that, but I'm a noob.

Also is there any way to upload poster/cover images easily?

**Comment by L4GSP1KE** [comment]
made it a little cleaner for ya.
What do you mean when you ask about uploading poster/cover images?

**Comment by LostRager** [comment]
> 

Our xxx category is using the other metadata, so it does not get poster/cover automatically, and you have to upload them manually. 

was wondering if the script could download the poster and cover from tmdb and upload it in the poser/cover area easily.
image

**Comment by L4GSP1KE** [comment]
This is not possible through the api from what I can tell.

**Pull request merged**
