### PR TITLE
Adding MTV

### PR DESCRIPTION
**Pull request by swannie-eire**
There is tonnes of data required to work fully but if users just enter their username and password and API key and then run L4G to upload to MTV in debug mode they will be able to get the info required to copy and paste into the config.py.

Screenshot 2022-12-12 at 8 20 02 a m

### CODE REVIEW

**Comment by mesol86** [comment]
This will be a great addition!

**Comment by L4GSP1KE** [comment]
Thanks! Appreciate the effort. I'm lazy and was waiting for the upload api :)
I will make a few ease of use/consistency commits soon™ before merging.

**Comment by Slikkster** [comment]
I'd be willing to be a tester for this tracker if needed.

**Comment by swannie-eire** [comment]
@L4GSP1KE 

Do you need me to do anything here to speed up merge?

**Comment by mesol86** [comment]
Waiting for this one to be merged..

**Pull request merged**
